<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="Central Standard Time">
<General productName="Vugen" productVer="12" os="" host="GV1GSLAP03"><DocLocation><![CDATA[C:\iDeliver\Scripts\July17\S01_DGS_GuestOrder_Wip0810]]></DocLocation></General>
<Doc rID="T1"   productName= "Vugen"  >
<DName><![CDATA[S01_DGS_GuestOrder_Wip0810]]></DName>
<Res><![CDATA[result1]]></Res>
<Action rID="T2">
<AName><![CDATA[Init]]></AName>
<Summary sTime="8/11/2017 - 11:50:12" eTime="8/11/2017 - 11:50:12" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="5" >
<Disp><![CDATA[Init Summary]]></Disp>
</NodeArgs>
</Action>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[Navigate]]></Obj>
<Details plainTxt="False" ><![CDATA[1: Navigate to http://qa.gamestop.com/ was finished]]></Details>
<Time><![CDATA[8/11/2017 - 11:50:17]]></Time>
<TimeTick>1502470217</TimeTick>
<NodeArgs eType="General" icon="0" nRep="9" status="Passed" >
<Disp><![CDATA[Navigate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[2: Click on Find games, consoles,... textbox was finished]]></Details>
<Time><![CDATA[8/11/2017 - 11:50:18]]></Time>
<TimeTick>1502470218</TimeTick>
<NodeArgs eType="General" icon="0" nRep="10" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[3: Type Test1235 in Find games, consoles,... textbox was finished]]></Details>
<Time><![CDATA[8/11/2017 - 11:50:24]]></Time>
<TimeTick>1502470224</TimeTick>
<NodeArgs eType="General" icon="0" nRep="11" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Press Key]]></Obj>
<Details plainTxt="False" ><![CDATA[4: Press Enter key on Find games, consoles,... textbox was finished]]></Details>
<Time><![CDATA[8/11/2017 - 11:51:23]]></Time>
<TimeTick>1502470283</TimeTick>
<NodeArgs eType="General" icon="0" nRep="12" status="Passed" >
<Disp><![CDATA[Press Key]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[5: Click on Add to Cart javascript_link was finished]]></Details>
<Time><![CDATA[8/11/2017 - 11:51:24]]></Time>
<TimeTick>1502470284</TimeTick>
<NodeArgs eType="General" icon="0" nRep="13" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[6: Click on Checkout link was finished]]></Details>
<Time><![CDATA[8/11/2017 - 11:51:27]]></Time>
<TimeTick>1502470287</TimeTick>
<NodeArgs eType="General" icon="0" nRep="14" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[8: Click on CONTINUE CHECKOUT ? link was finished]]></Details>
<Time><![CDATA[8/11/2017 - 11:51:33]]></Time>
<TimeTick>1502470293</TimeTick>
<NodeArgs eType="General" icon="0" nRep="15" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[9: Click on CONTINUE AS GUEST link was finished]]></Details>
<Time><![CDATA[8/11/2017 - 11:51:35]]></Time>
<TimeTick>1502470295</TimeTick>
<NodeArgs eType="General" icon="0" nRep="16" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[10: Click on First Name textbox was finished]]></Details>
<Time><![CDATA[8/11/2017 - 11:51:36]]></Time>
<TimeTick>1502470296</TimeTick>
<NodeArgs eType="General" icon="0" nRep="17" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[11: Type accept in First Name textbox was finished]]></Details>
<Time><![CDATA[8/11/2017 - 11:51:38]]></Time>
<TimeTick>1502470298</TimeTick>
<NodeArgs eType="General" icon="0" nRep="18" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[12: Type accept in Last Name textbox was finished]]></Details>
<Time><![CDATA[8/11/2017 - 11:51:41]]></Time>
<TimeTick>1502470301</TimeTick>
<NodeArgs eType="General" icon="0" nRep="19" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[13: Type 625 westport pkwy in Address 1 textbox was finished]]></Details>
<Time><![CDATA[8/11/2017 - 11:51:48]]></Time>
<TimeTick>1502470308</TimeTick>
<NodeArgs eType="General" icon="0" nRep="20" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[14: Type grapevine in City textbox was finished]]></Details>
<Time><![CDATA[8/11/2017 - 11:52:09]]></Time>
<TimeTick>1502470329</TimeTick>
<NodeArgs eType="General" icon="0" nRep="21" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Select]]></Obj>
<Details plainTxt="False" ><![CDATA[15: Select Texas from State/Province listbox was finished]]></Details>
<Time><![CDATA[8/11/2017 - 11:52:09]]></Time>
<TimeTick>1502470329</TimeTick>
<NodeArgs eType="General" icon="0" nRep="22" status="Passed" >
<Disp><![CDATA[Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[16: Type 76051 in Zip/Postal textbox was finished]]></Details>
<Time><![CDATA[8/11/2017 - 11:52:11]]></Time>
<TimeTick>1502470331</TimeTick>
<NodeArgs eType="General" icon="0" nRep="23" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[17: Type 8177227584 in Phone Number textbox was finished]]></Details>
<Time><![CDATA[8/11/2017 - 11:52:17]]></Time>
<TimeTick>1502470337</TimeTick>
<NodeArgs eType="General" icon="0" nRep="24" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[18: Type gamestop.soasta.0001@gmail.com in Purchaser's Email textbox was finished]]></Details>
<Time><![CDATA[8/11/2017 - 11:52:28]]></Time>
<TimeTick>1502470348</TimeTick>
<NodeArgs eType="General" icon="0" nRep="25" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Scroll into View]]></Obj>
<Details plainTxt="False" ><![CDATA[19: Scroll CONTINUE CHECKOUT ?  into view was finished]]></Details>
<Time><![CDATA[8/11/2017 - 11:52:29]]></Time>
<TimeTick>1502470349</TimeTick>
<NodeArgs eType="General" icon="0" nRep="26" status="Passed" >
<Disp><![CDATA[Scroll into View]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[21: Click on CONTINUE CHECKOUT ?  was finished]]></Details>
<Time><![CDATA[8/11/2017 - 11:52:30]]></Time>
<TimeTick>1502470350</TimeTick>
<NodeArgs eType="General" icon="0" nRep="27" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Scroll into View]]></Obj>
<Details plainTxt="False" ><![CDATA[25: Scroll We are committed to protecting...  into view was finished]]></Details>
<Time><![CDATA[8/11/2017 - 11:52:55]]></Time>
<TimeTick>1502470375</TimeTick>
<NodeArgs eType="General" icon="0" nRep="28" status="Passed" >
<Disp><![CDATA[Scroll into View]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[27: Click on CONTINUE CHECKOUT ?  was finished]]></Details>
<Time><![CDATA[8/11/2017 - 11:53:02]]></Time>
<TimeTick>1502470382</TimeTick>
<NodeArgs eType="General" icon="0" nRep="29" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Scroll into View]]></Obj>
<Details plainTxt="False" ><![CDATA[30: Scroll SUBMIT ORDER  into view was finished]]></Details>
<Time><![CDATA[8/11/2017 - 11:53:06]]></Time>
<TimeTick>1502470386</TimeTick>
<NodeArgs eType="General" icon="0" nRep="30" status="Passed" >
<Disp><![CDATA[Scroll into View]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Select]]></Obj>
<Details plainTxt="False" ><![CDATA[31: Select Visa from CardType listbox was finished]]></Details>
<Time><![CDATA[8/11/2017 - 11:53:07]]></Time>
<TimeTick>1502470387</TimeTick>
<NodeArgs eType="General" icon="0" nRep="31" status="Passed" >
<Disp><![CDATA[Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[32: Click on Use another payment type... textbox was finished]]></Details>
<Time><![CDATA[8/11/2017 - 11:53:08]]></Time>
<TimeTick>1502470388</TimeTick>
<NodeArgs eType="General" icon="0" nRep="32" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[33: Type 4444333322221111 in Use another payment type... textbox was finished]]></Details>
<Time><![CDATA[8/11/2017 - 11:53:15]]></Time>
<TimeTick>1502470395</TimeTick>
<NodeArgs eType="General" icon="0" nRep="33" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Select]]></Obj>
<Details plainTxt="False" ><![CDATA[34: Select 08 from Expires listbox was finished]]></Details>
<Time><![CDATA[8/11/2017 - 11:53:15]]></Time>
<TimeTick>1502470395</TimeTick>
<NodeArgs eType="General" icon="0" nRep="34" status="Passed" >
<Disp><![CDATA[Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Select]]></Obj>
<Details plainTxt="False" ><![CDATA[35: Select 2020 from 010203040506070809101112 listbox was finished]]></Details>
<Time><![CDATA[8/11/2017 - 11:53:16]]></Time>
<TimeTick>1502470396</TimeTick>
<NodeArgs eType="General" icon="0" nRep="35" status="Passed" >
<Disp><![CDATA[Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[36: Click on Security Code: What's... textbox was finished]]></Details>
<Time><![CDATA[8/11/2017 - 11:53:17]]></Time>
<TimeTick>1502470397</TimeTick>
<NodeArgs eType="General" icon="0" nRep="36" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[37: Type 123 in Security Code: What's... textbox was finished]]></Details>
<Time><![CDATA[8/11/2017 - 11:53:18]]></Time>
<TimeTick>1502470398</TimeTick>
<NodeArgs eType="General" icon="0" nRep="37" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[38: Click on SUBMIT ORDER  was finished]]></Details>
<Time><![CDATA[8/11/2017 - 11:53:25]]></Time>
<TimeTick>1502470405</TimeTick>
<NodeArgs eType="General" icon="0" nRep="38" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[Wait]]></Obj>
<Details plainTxt="False" ><![CDATA[40: Wait for Thanks for your order! heading was finished]]></Details>
<Time><![CDATA[8/11/2017 - 11:53:31]]></Time>
<TimeTick>1502470411</TimeTick>
<NodeArgs eType="General" icon="0" nRep="39" status="Passed" >
<Disp><![CDATA[Wait]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[40.1: Click on No, Thanks  was finished]]></Details>
<Time><![CDATA[8/11/2017 - 11:53:32]]></Time>
<TimeTick>1502470412</TimeTick>
<NodeArgs eType="General" icon="0" nRep="40" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[42: Click on Your Order Number:  was finished]]></Details>
<Time><![CDATA[8/11/2017 - 11:53:36]]></Time>
<TimeTick>1502470416</TimeTick>
<NodeArgs eType="General" icon="0" nRep="41" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[Evaluate JavaScript]]></Obj>
<Details plainTxt="False" ><![CDATA[44: Evaluate JavaScript var text = object.textCo...rs",randomText); on Your Order Number:  was finished]]></Details>
<Time><![CDATA[8/11/2017 - 11:53:40]]></Time>
<TimeTick>1502470420</TimeTick>
<NodeArgs eType="General" icon="0" nRep="42" status="Passed" >
<Disp><![CDATA[Evaluate JavaScript]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="8/11/2017 - 11:50:12" eTime="8/11/2017 - 11:53:40" passed="34" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="8" status="Passed" >
<Disp><![CDATA[Action Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T39">
<AName><![CDATA[SSMQ]]></AName>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[Navigate]]></Obj>
<Details plainTxt="False" ><![CDATA[1: Navigate to qa.gamestop.com was finished]]></Details>
<Time><![CDATA[8/11/2017 - 11:53:43]]></Time>
<TimeTick>1502470423</TimeTick>
<NodeArgs eType="General" icon="0" nRep="45" status="Passed" >
<Disp><![CDATA[Navigate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[2: Click on Find games, consoles,... textbox was finished]]></Details>
<Time><![CDATA[8/11/2017 - 11:53:44]]></Time>
<TimeTick>1502470424</TimeTick>
<NodeArgs eType="General" icon="0" nRep="46" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[3: Type Test1236 in Find games, consoles,... textbox was finished]]></Details>
<Time><![CDATA[8/11/2017 - 11:53:48]]></Time>
<TimeTick>1502470428</TimeTick>
<NodeArgs eType="General" icon="0" nRep="47" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[Press Key]]></Obj>
<Details plainTxt="False" ><![CDATA[4: Press Enter key on Find games, consoles,... textbox was finished]]></Details>
<Time><![CDATA[8/11/2017 - 11:53:51]]></Time>
<TimeTick>1502470431</TimeTick>
<NodeArgs eType="General" icon="0" nRep="48" status="Passed" >
<Disp><![CDATA[Press Key]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[5: Click on Add to Cart javascript_link was finished]]></Details>
<Time><![CDATA[8/11/2017 - 11:53:53]]></Time>
<TimeTick>1502470433</TimeTick>
<NodeArgs eType="General" icon="0" nRep="49" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[6: Click on Checkout link was finished]]></Details>
<Time><![CDATA[8/11/2017 - 11:53:57]]></Time>
<TimeTick>1502470437</TimeTick>
<NodeArgs eType="General" icon="0" nRep="50" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[7: Click on 1 textbox was finished]]></Details>
<Time><![CDATA[8/11/2017 - 11:53:58]]></Time>
<TimeTick>1502470438</TimeTick>
<NodeArgs eType="General" icon="0" nRep="51" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[8: Type 3 in 1 textbox was finished]]></Details>
<Time><![CDATA[8/11/2017 - 11:53:59]]></Time>
<TimeTick>1502470439</TimeTick>
<NodeArgs eType="General" icon="0" nRep="52" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[9: Click on Update  was finished]]></Details>
<Time><![CDATA[8/11/2017 - 11:54:01]]></Time>
<TimeTick>1502470441</TimeTick>
<NodeArgs eType="General" icon="0" nRep="53" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[10: Click on CONTINUE CHECKOUT ? link was finished]]></Details>
<Time><![CDATA[8/11/2017 - 11:54:03]]></Time>
<TimeTick>1502470443</TimeTick>
<NodeArgs eType="General" icon="0" nRep="54" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[12: Click on CONTINUE AS GUEST link was finished]]></Details>
<Time><![CDATA[8/11/2017 - 11:54:09]]></Time>
<TimeTick>1502470449</TimeTick>
<NodeArgs eType="General" icon="0" nRep="55" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[13: Click on First Name textbox was finished]]></Details>
<Time><![CDATA[8/11/2017 - 11:54:10]]></Time>
<TimeTick>1502470450</TimeTick>
<NodeArgs eType="General" icon="0" nRep="56" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[14: Type accept in First Name textbox was finished]]></Details>
<Time><![CDATA[8/11/2017 - 11:54:13]]></Time>
<TimeTick>1502470453</TimeTick>
<NodeArgs eType="General" icon="0" nRep="57" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[15: Type accept in Last Name textbox was finished]]></Details>
<Time><![CDATA[8/11/2017 - 11:54:16]]></Time>
<TimeTick>1502470456</TimeTick>
<NodeArgs eType="General" icon="0" nRep="58" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[16: Type 625 westport pkwy in Address 1 textbox was finished]]></Details>
<Time><![CDATA[8/11/2017 - 11:54:24]]></Time>
<TimeTick>1502470464</TimeTick>
<NodeArgs eType="General" icon="0" nRep="59" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[17: Type grapevine in City textbox was finished]]></Details>
<Time><![CDATA[8/11/2017 - 11:54:27]]></Time>
<TimeTick>1502470467</TimeTick>
<NodeArgs eType="General" icon="0" nRep="60" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[Select]]></Obj>
<Details plainTxt="False" ><![CDATA[18: Select Texas from State/Province listbox was finished]]></Details>
<Time><![CDATA[8/11/2017 - 11:54:27]]></Time>
<TimeTick>1502470467</TimeTick>
<NodeArgs eType="General" icon="0" nRep="61" status="Passed" >
<Disp><![CDATA[Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[19: Click on Zip/Postal textbox was finished]]></Details>
<Time><![CDATA[8/11/2017 - 11:54:28]]></Time>
<TimeTick>1502470468</TimeTick>
<NodeArgs eType="General" icon="0" nRep="62" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[20: Type 76051 in Zip/Postal textbox was finished]]></Details>
<Time><![CDATA[8/11/2017 - 11:54:32]]></Time>
<TimeTick>1502470472</TimeTick>
<NodeArgs eType="General" icon="0" nRep="63" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[21: Click on Phone Number textbox was finished]]></Details>
<Time><![CDATA[8/11/2017 - 11:54:33]]></Time>
<TimeTick>1502470473</TimeTick>
<NodeArgs eType="General" icon="0" nRep="64" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[22: Type 8177227584 in Phone Number textbox was finished]]></Details>
<Time><![CDATA[8/11/2017 - 11:54:37]]></Time>
<TimeTick>1502470477</TimeTick>
<NodeArgs eType="General" icon="0" nRep="65" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[23: Click on Purchaser's Email textbox was finished]]></Details>
<Time><![CDATA[8/11/2017 - 11:54:38]]></Time>
<TimeTick>1502470478</TimeTick>
<NodeArgs eType="General" icon="0" nRep="66" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[24: Type gamestop.soasta.0001@gmail.com in Purchaser's Email textbox was finished]]></Details>
<Time><![CDATA[8/11/2017 - 11:54:50]]></Time>
<TimeTick>1502470490</TimeTick>
<NodeArgs eType="General" icon="0" nRep="67" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[25: Click on CONTINUE CHECKOUT ?  was finished]]></Details>
<Time><![CDATA[8/11/2017 - 11:54:51]]></Time>
<TimeTick>1502470491</TimeTick>
<NodeArgs eType="General" icon="0" nRep="68" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA[Scroll into View]]></Obj>
<Details plainTxt="False" ><![CDATA[27: Scroll We are committed to protecting...  into view was finished]]></Details>
<Time><![CDATA[8/11/2017 - 11:54:55]]></Time>
<TimeTick>1502470495</TimeTick>
<NodeArgs eType="General" icon="0" nRep="69" status="Passed" >
<Disp><![CDATA[Scroll into View]]></Disp>
</NodeArgs>
</Step>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[28: Click on CONTINUE CHECKOUT ?  was finished]]></Details>
<Time><![CDATA[8/11/2017 - 11:54:58]]></Time>
<TimeTick>1502470498</TimeTick>
<NodeArgs eType="General" icon="0" nRep="70" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T66">
<Obj plainTxt="False" ><![CDATA[Select]]></Obj>
<Details plainTxt="False" ><![CDATA[29: Select Visa from CardType listbox was finished]]></Details>
<Time><![CDATA[8/11/2017 - 11:54:58]]></Time>
<TimeTick>1502470498</TimeTick>
<NodeArgs eType="General" icon="0" nRep="71" status="Passed" >
<Disp><![CDATA[Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T67">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[30: Click on Use another payment type... textbox was finished]]></Details>
<Time><![CDATA[8/11/2017 - 11:54:59]]></Time>
<TimeTick>1502470499</TimeTick>
<NodeArgs eType="General" icon="0" nRep="72" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T68">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[31: Type 4444333322221111 in Use another payment type... textbox was finished]]></Details>
<Time><![CDATA[8/11/2017 - 11:55:10]]></Time>
<TimeTick>1502470510</TimeTick>
<NodeArgs eType="General" icon="0" nRep="73" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T69">
<Obj plainTxt="False" ><![CDATA[Select]]></Obj>
<Details plainTxt="False" ><![CDATA[32: Select 08 from Expires listbox was finished]]></Details>
<Time><![CDATA[8/11/2017 - 11:55:10]]></Time>
<TimeTick>1502470510</TimeTick>
<NodeArgs eType="General" icon="0" nRep="74" status="Passed" >
<Disp><![CDATA[Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T70">
<Obj plainTxt="False" ><![CDATA[Select]]></Obj>
<Details plainTxt="False" ><![CDATA[33: Select 2020 from 010203040506070809101112 listbox was finished]]></Details>
<Time><![CDATA[8/11/2017 - 11:55:11]]></Time>
<TimeTick>1502470511</TimeTick>