<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="Central Standard Time">
<General productName="Vugen" productVer="12" os="" host="USGVLJ954KC2"><DocLocation><![CDATA[C:\Users\casmith\Documents\VuGen\Scripts\Bronze3\LoyaltyPointsService]]></DocLocation></General>
<Doc rID="T1"   productName= "Vugen"  >
<DName><![CDATA[LoyaltyPointsService]]></DName>
<Res><![CDATA[result1]]></Res>
<Action rID="T2">
<AName><![CDATA[vuser_init]]></AName>
<Summary sTime="2/22/2017 - 11:33:58" eTime="2/22/2017 - 11:33:58" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="5" >
<Disp><![CDATA[vuser_init Summary]]></Disp>
</NodeArgs>
</Action>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[GetAllPointsHistory_102]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Web service call was successful</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[2/22/2017 - 11:33:59]]></Time>
<TimeTick>1487784839</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[HTTP Traffic]]></Obj>
<Details plainTxt="False" ><![CDATA[HTTP Traffic]]></Details>
<Time><![CDATA[2/22/2017 - 11:33:59]]></Time>
<TimeTick>1487784839</TimeTick>
<NodeArgs eType="General" icon="4" nRep="10" >
<Disp><![CDATA[HTTP Traffic]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t1_http.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="General" icon="4" nRep="9" status="Passed" >
<Disp><![CDATA[GetAllPointsHistory_102]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t0_web_service_call.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[GetPointsBalance_103]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Web service call was successful</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[2/22/2017 - 11:33:59]]></Time>
<TimeTick>1487784839</TimeTick>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[HTTP Traffic]]></Obj>
<Details plainTxt="False" ><![CDATA[HTTP Traffic]]></Details>
<Time><![CDATA[2/22/2017 - 11:33:59]]></Time>
<TimeTick>1487784839</TimeTick>
<NodeArgs eType="General" icon="4" nRep="12" >
<Disp><![CDATA[HTTP Traffic]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t2_http.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="General" icon="4" nRep="11" status="Passed" >
<Disp><![CDATA[GetPointsBalance_103]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t1_web_service_call.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[GetPointsHistory_102]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Web service call was successful</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[2/22/2017 - 11:33:59]]></Time>
<TimeTick>1487784839</TimeTick>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[HTTP Traffic]]></Obj>
<Details plainTxt="False" ><![CDATA[HTTP Traffic]]></Details>
<Time><![CDATA[2/22/2017 - 11:33:59]]></Time>
<TimeTick>1487784839</TimeTick>
<NodeArgs eType="General" icon="4" nRep="14" >
<Disp><![CDATA[HTTP Traffic]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t3_http.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="General" icon="4" nRep="13" status="Passed" >
<Disp><![CDATA[GetPointsHistory_102]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t2_web_service_call.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[GetPointSubTypes_102]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Web service call was successful</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[2/22/2017 - 11:33:59]]></Time>
<TimeTick>1487784839</TimeTick>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[HTTP Traffic]]></Obj>
<Details plainTxt="False" ><![CDATA[HTTP Traffic]]></Details>
<Time><![CDATA[2/22/2017 - 11:33:59]]></Time>
<TimeTick>1487784839</TimeTick>
<NodeArgs eType="General" icon="4" nRep="16" >
<Disp><![CDATA[HTTP Traffic]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t4_http.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="General" icon="4" nRep="15" status="Passed" >
<Disp><![CDATA[GetPointSubTypes_102]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t3_web_service_call.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[IsServiceHealthy_101]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Web service call was successful</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[2/22/2017 - 11:33:59]]></Time>
<TimeTick>1487784839</TimeTick>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[HTTP Traffic]]></Obj>
<Details plainTxt="False" ><![CDATA[HTTP Traffic]]></Details>
<Time><![CDATA[2/22/2017 - 11:33:59]]></Time>
<TimeTick>1487784839</TimeTick>
<NodeArgs eType="General" icon="4" nRep="18" >
<Disp><![CDATA[HTTP Traffic]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t5_http.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="General" icon="4" nRep="17" status="Passed" >
<Disp><![CDATA[IsServiceHealthy_101]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t4_web_service_call.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[SendPointsActivity_101]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Web service call was successful</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[2/22/2017 - 11:33:59]]></Time>
<TimeTick>1487784839</TimeTick>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[HTTP Traffic]]></Obj>
<Details plainTxt="False" ><![CDATA[HTTP Traffic]]></Details>
<Time><![CDATA[2/22/2017 - 11:33:59]]></Time>
<TimeTick>1487784839</TimeTick>
<NodeArgs eType="General" icon="4" nRep="20" >
<Disp><![CDATA[HTTP Traffic]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t6_http.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="General" icon="4" nRep="19" status="Passed" >
<Disp><![CDATA[SendPointsActivity_101]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t5_web_service_call.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Summary sTime="2/22/2017 - 11:33:58" eTime="2/22/2017 - 11:33:59" passed="6" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="8" status="Passed" >
<Disp><![CDATA[Action Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T17">
<AName><![CDATA[GetPointsHistory]]></AName>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[GetPointsHistory_101]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Web service call was successful</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[2/22/2017 - 11:33:59]]></Time>
<TimeTick>1487784839</TimeTick>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[HTTP Traffic]]></Obj>
<Details plainTxt="False" ><![CDATA[HTTP Traffic]]></Details>
<Time><![CDATA[2/22/2017 - 11:33:59]]></Time>
<TimeTick>1487784839</TimeTick>
<NodeArgs eType="General" icon="4" nRep="24" >
<Disp><![CDATA[HTTP Traffic]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t7_http.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="General" icon="4" nRep="23" status="Passed" >
<Disp><![CDATA[GetPointsHistory_101]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t6_web_service_call.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Summary sTime="2/22/2017 - 11:33:59" eTime="2/22/2017 - 11:33:59" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="22" status="Passed" >
<Disp><![CDATA[GetPointsHistory Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="7" status="Passed" >
<Disp><![CDATA[LoyaltyPointsService Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Action rID="T20">
<AName><![CDATA[vuser_end]]></AName>
<Summary sTime="2/22/2017 - 11:33:59" eTime="2/22/2017 - 11:33:59" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="27" >
<Disp><![CDATA[vuser_end Summary]]></Disp>
</NodeArgs>
</Action>
<Summary sTime="2/22/2017 - 11:33:58" eTime="2/22/2017 - 11:33:59" passed="7" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="4" status="Passed" >
<Disp><![CDATA[Test LoyaltyPointsService Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>