<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="Central Standard Time">
<General productName="Vugen" productVer="12" os="" host="USGVLJ954KC2"><DocLocation><![CDATA[C:\Users\casmith\Documents\VuGen\Scripts\Bronze4\CSLStoreAdministrationService]]></DocLocation></General>
<Doc rID="T1"   productName= "Vugen"  >
<DName><![CDATA[CSLStoreAdministrationService]]></DName>
<Res><![CDATA[result1]]></Res>
<Action rID="T2">
<AName><![CDATA[vuser_init]]></AName>
<Summary sTime="1/17/2017 - 12:03:50" eTime="1/17/2017 - 12:03:50" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="5" >
<Disp><![CDATA[vuser_init Summary]]></Disp>
</NodeArgs>
</Action>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[GetOrganizationHirearchy]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[GetOrganizationHierarchy_101]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Web service call was successful</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[1/17/2017 - 12:04:00]]></Time>
<TimeTick>1484676240</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[HTTP Traffic]]></Obj>
<Details plainTxt="False" ><![CDATA[HTTP Traffic]]></Details>
<Time><![CDATA[1/17/2017 - 12:04:00]]></Time>
<TimeTick>1484676240</TimeTick>
<NodeArgs eType="General" icon="4" nRep="10" >
<Disp><![CDATA[HTTP Traffic]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t1_http.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="General" icon="4" nRep="9" status="Passed" >
<Disp><![CDATA[GetOrganizationHierarchy_101]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t0_web_service_call.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Summary sTime="1/17/2017 - 12:03:50" eTime="1/17/2017 - 12:04:00" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="8" status="Passed" >
<Disp><![CDATA[GetOrganizationHirearchy Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T7">
<AName><![CDATA[GetOrganizationHierarchyByCompany]]></AName>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[GetOrganizationHierarchyByCompany_101]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Web service call was successful</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[1/17/2017 - 12:04:01]]></Time>
<TimeTick>1484676241</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[HTTP Traffic]]></Obj>
<Details plainTxt="False" ><![CDATA[HTTP Traffic]]></Details>
<Time><![CDATA[1/17/2017 - 12:04:01]]></Time>
<TimeTick>1484676241</TimeTick>
<NodeArgs eType="General" icon="4" nRep="14" >
<Disp><![CDATA[HTTP Traffic]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t2_http.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="General" icon="4" nRep="13" status="Passed" >
<Disp><![CDATA[GetOrganizationHierarchyByCompany_101]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t1_web_service_call.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Summary sTime="1/17/2017 - 12:04:00" eTime="1/17/2017 - 12:04:01" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="12" status="Passed" >
<Disp><![CDATA[GetOrganizationHierarchyByCompany Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T10">
<AName><![CDATA[GetOrganizationHierarchyByCountry]]></AName>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[GetOrganizationHierarchyByCountry_101]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Web service call was successful</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[1/17/2017 - 12:04:01]]></Time>
<TimeTick>1484676241</TimeTick>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[HTTP Traffic]]></Obj>
<Details plainTxt="False" ><![CDATA[HTTP Traffic]]></Details>
<Time><![CDATA[1/17/2017 - 12:04:01]]></Time>
<TimeTick>1484676241</TimeTick>
<NodeArgs eType="General" icon="4" nRep="18" >
<Disp><![CDATA[HTTP Traffic]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t3_http.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="General" icon="4" nRep="17" status="Passed" >
<Disp><![CDATA[GetOrganizationHierarchyByCountry_101]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t2_web_service_call.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Summary sTime="1/17/2017 - 12:04:01" eTime="1/17/2017 - 12:04:01" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="16" status="Passed" >
<Disp><![CDATA[GetOrganizationHierarchyByCountry Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T13">
<AName><![CDATA[GetOrganizationHierarchyByCountryZone]]></AName>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[GetOrganizationHierarchyByCountryZone_101]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Web service call was successful</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[1/17/2017 - 12:04:10]]></Time>
<TimeTick>1484676250</TimeTick>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[HTTP Traffic]]></Obj>
<Details plainTxt="False" ><![CDATA[HTTP Traffic]]></Details>
<Time><![CDATA[1/17/2017 - 12:04:11]]></Time>
<TimeTick>1484676251</TimeTick>
<NodeArgs eType="General" icon="4" nRep="22" >
<Disp><![CDATA[HTTP Traffic]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t4_http.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="General" icon="4" nRep="21" status="Passed" >
<Disp><![CDATA[GetOrganizationHierarchyByCountryZone_101]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t3_web_service_call.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Summary sTime="1/17/2017 - 12:04:01" eTime="1/17/2017 - 12:04:11" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="20" status="Passed" >
<Disp><![CDATA[GetOrganizationHierarchyByCountryZone Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T16">
<AName><![CDATA[GetOrganizationHierarchyByDistrict]]></AName>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[GetOrganizationHierarchyByDistrict_101]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Web service call was successful</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[1/17/2017 - 12:04:12]]></Time>
<TimeTick>1484676252</TimeTick>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[HTTP Traffic]]></Obj>
<Details plainTxt="False" ><![CDATA[HTTP Traffic]]></Details>
<Time><![CDATA[1/17/2017 - 12:04:12]]></Time>
<TimeTick>1484676252</TimeTick>
<NodeArgs eType="General" icon="4" nRep="26" >
<Disp><![CDATA[HTTP Traffic]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t5_http.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="General" icon="4" nRep="25" status="Passed" >
<Disp><![CDATA[GetOrganizationHierarchyByDistrict_101]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t4_web_service_call.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Summary sTime="1/17/2017 - 12:04:11" eTime="1/17/2017 - 12:04:12" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="24" status="Passed" >
<Disp><![CDATA[GetOrganizationHierarchyByDistrict Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T19">
<AName><![CDATA[GetOrganizationHierarchyByMarket]]></AName>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[GetOrganizationHierarchyByMarket_101]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Web service call was successful</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[1/17/2017 - 12:04:14]]></Time>
<TimeTick>1484676254</TimeTick>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[HTTP Traffic]]></Obj>
<Details plainTxt="False" ><![CDATA[HTTP Traffic]]></Details>
<Time><![CDATA[1/17/2017 - 12:04:15]]></Time>
<TimeTick>1484676255</TimeTick>
<NodeArgs eType="General" icon="4" nRep="30" >
<Disp><![CDATA[HTTP Traffic]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t6_http.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="General" icon="4" nRep="29" status="Passed" >
<Disp><![CDATA[GetOrganizationHierarchyByMarket_101]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t5_web_service_call.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Summary sTime="1/17/2017 - 12:04:12" eTime="1/17/2017 - 12:04:15" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="28" status="Passed" >
<Disp><![CDATA[GetOrganizationHierarchyByMarket Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T22">
<AName><![CDATA[GetOrganizationHierarchyByRegion]]></AName>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[GetOrganizationHierarchyByRegion_101]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Web service call was successful</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[1/17/2017 - 12:04:15]]></Time>
<TimeTick>1484676255</TimeTick>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[HTTP Traffic]]></Obj>
<Details plainTxt="False" ><![CDATA[HTTP Traffic]]></Details>
<Time><![CDATA[1/17/2017 - 12:04:15]]></Time>
<TimeTick>1484676255</TimeTick>
<NodeArgs eType="General" icon="4" nRep="34" >
<Disp><![CDATA[HTTP Traffic]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t7_http.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="General" icon="4" nRep="33" status="Passed" >
<Disp><![CDATA[GetOrganizationHierarchyByRegion_101]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t6_web_service_call.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Summary sTime="1/17/2017 - 12:04:15" eTime="1/17/2017 - 12:04:15" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="32" status="Passed" >
<Disp><![CDATA[GetOrganizationHierarchyByRegion Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T25">
<AName><![CDATA[GetOrganizationHierarchyByStore]]></AName>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[GetOrganizationHierarchyByStore_101]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Web service call was successful</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[1/17/2017 - 12:04:16]]></Time>
<TimeTick>1484676256</TimeTick>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[HTTP Traffic]]></Obj>
<Details plainTxt="False" ><![CDATA[HTTP Traffic]]></Details>
<Time><![CDATA[1/17/2017 - 12:04:16]]></Time>
<TimeTick>1484676256</TimeTick>
<NodeArgs eType="General" icon="4" nRep="38" >
<Disp><![CDATA[HTTP Traffic]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t8_http.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="General" icon="4" nRep="37" status="Passed" >
<Disp><![CDATA[GetOrganizationHierarchyByStore_101]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t7_web_service_call.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Summary sTime="1/17/2017 - 12:04:15" eTime="1/17/2017 - 12:04:16" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="36" status="Passed" >
<Disp><![CDATA[GetOrganizationHierarchyByStore Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T28">
<AName><![CDATA[GetOrganizationHierarchyFlat]]></AName>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[GetOrganizationHierarchyFlat_101]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Web service call was successful</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[1/17/2017 - 12:04:33]]></Time>
<TimeTick>1484676273</TimeTick>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[HTTP Traffic]]></Obj>
<Details plainTxt="False" ><![CDATA[HTTP Traffic]]></Details>
<Time><![CDATA[1/17/2017 - 12:04:33]]></Time>
<TimeTick>1484676273</TimeTick>
<NodeArgs eType="General" icon="4" nRep="42" >
<Disp><![CDATA[HTTP Traffic]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t9_http.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="General" icon="4" nRep="41" status="Passed" >
<Disp><![CDATA[GetOrganizationHierarchyFlat_101]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t8_web_service_call.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Summary sTime="1/17/2017 - 12:04:16" eTime="1/17/2017 - 12:04:33" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="40" status="Passed" >
<Disp><![CDATA[GetOrganizationHierarchyFlat Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T31">
<AName><![CDATA[GetVersion]]></AName>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[GetVersion_103]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Web service call was successful</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[1/17/2017 - 12:04:33]]></Time>
<TimeTick>1484676273</TimeTick>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[HTTP Traffic]]></Obj>
<Details plainTxt="False" ><![CDATA[HTTP Traffic]]></Details>
<Time><![CDATA[1/17/2017 - 12:04:33]]></Time>
<TimeTick>1484676273</TimeTick>
<NodeArgs eType="General" icon="4" nRep="46" >
<Disp><![CDATA[HTTP Traffic]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t10_http.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="General" icon="4" nRep="45" status="Passed" >
<Disp><![CDATA[GetVersion_103]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t9_web_service_call.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Summary sTime="1/17/2017 - 12:04:33" eTime="1/17/2017 - 12:04:33" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="44" status="Passed" >
<Disp><![CDATA[GetVersion Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T34">
<AName><![CDATA[IsServiceAlive]]></AName>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[IsServiceAlive_103]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Web service call was successful</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[1/17/2017 - 12:04:34]]></Time>
<TimeTick>1484676274</TimeTick>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[HTTP Traffic]]></Obj>
<Details plainTxt="False" ><![CDATA[HTTP Traffic]]></Details>
<Time><![CDATA[1/17/2017 - 12:04:34]]></Time>
<TimeTick>1484676274</TimeTick>
<NodeArgs eType="General" icon="4" nRep="50" >
<Disp><![CDATA[HTTP Traffic]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t11_http.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="General" icon="4" nRep="49" status="Passed" >
<Disp><![CDATA[IsServiceAlive_103]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t10_web_service_call.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Summary sTime="1/17/2017 - 12:04:33" eTime="1/17/2017 - 12:04:34" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="48" status="Passed" >
<Disp><![CDATA[IsServiceAlive Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T37">
<AName><![CDATA[IsServiceHealthy]]></AName>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[IsServiceHealthy_103]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Web service call was successful</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[1/17/2017 - 12:04:34]]></Time>
<TimeTick>1484676274</TimeTick>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[HTTP Traffic]]></Obj>
<Details plainTxt="False" ><![CDATA[HTTP Traffic]]></Details>
<Time><![CDATA[1/17/2017 - 12:04:34]]></Time>
<TimeTick>1484676274</TimeTick>
<NodeArgs eType="General" icon="4" nRep="54" >
<Disp><![CDATA[HTTP Traffic]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t12_http.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="General" icon="4" nRep="53" status="Passed" >
<Disp><![CDATA[IsServiceHealthy_103]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t11_web_service_call.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[IsServiceHealthy_104]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Web service call was successful</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[1/17/2017 - 12:04:34]]></Time>
<TimeTick>1484676274</TimeTick>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[HTTP Traffic]]></Obj>
<Details plainTxt="False" ><![CDATA[HTTP Traffic]]></Details>
<Time><![CDATA[1/17/2017 - 12:04:34]]></Time>
<TimeTick>1484676274</TimeTick>
<NodeArgs eType="General" icon="4" nRep="56" >
<Disp><![CDATA[HTTP Traffic]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t13_http.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="General" icon="4" nRep="55" status="Passed" >
<Disp><![CDATA[IsServiceHealthy_104]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t12_web_service_call.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Summary sTime="1/17/2017 - 12:04:34" eTime="1/17/2017 - 12:04:34" passed="2" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="52" status="Passed" >
<Disp><![CDATA[IsServiceHealthy Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="7" status="Passed" >
<Disp><![CDATA[CSLStoreAdministrationService Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Action rID="T42">
<AName><![CDATA[vuser_end]]></AName>
<Summary sTime="1/17/2017 - 12:04:34" eTime="1/17/2017 - 12:04:34" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="59" >
<Disp><![CDATA[vuser_end Summary]]></Disp>
</NodeArgs>
</Action>
<Summary sTime="1/17/2017 - 12:03:50" eTime="1/17/2017 - 12:04:34" passed="13" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="4" status="Passed" >
<Disp><![CDATA[Test CSLStoreAdministrationService Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>