<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="Central Standard Time">
<General productName="Vugen" productVer="12" os="" host="USGVLJ954KC2"><DocLocation><![CDATA[C:\Users\casmith\Documents\VuGen\Scripts\Bronze3\CSLOfferService]]></DocLocation></General>
<Doc rID="T1"   productName= "Vugen"  >
<DName><![CDATA[CSLOfferService]]></DName>
<Res><![CDATA[result1]]></Res>
<Action rID="T2">
<AName><![CDATA[vuser_init]]></AName>
<Summary sTime="7/27/2017 - 11:55:06" eTime="7/27/2017 - 11:55:06" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="5" >
<Disp><![CDATA[vuser_init Summary]]></Disp>
</NodeArgs>
</Action>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[CreateOfferForCustomer]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[CreateOfferForCustomer_102]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Web service call was successful</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[7/27/2017 - 11:55:09]]></Time>
<TimeTick>1501174509</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[HTTP Traffic]]></Obj>
<Details plainTxt="False" ><![CDATA[HTTP Traffic]]></Details>
<Time><![CDATA[7/27/2017 - 11:55:09]]></Time>
<TimeTick>1501174509</TimeTick>
<NodeArgs eType="General" icon="4" nRep="10" >
<Disp><![CDATA[HTTP Traffic]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t1_http.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="General" icon="4" nRep="9" status="Passed" >
<Disp><![CDATA[CreateOfferForCustomer_102]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t0_web_service_call.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA["lr_xml_get_values"]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>"lr_xml_get_values" succeeded</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[7/27/2017 - 11:55:09]]></Time>
<TimeTick>1501174509</TimeTick>
<NodeArgs eType="General" icon="5" nRep="11" status="Passed" >
<Disp><![CDATA["lr_xml_get_values"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA["lr_xml_get_values"]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>"lr_xml_get_values" succeeded</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[7/27/2017 - 11:55:09]]></Time>
<TimeTick>1501174509</TimeTick>
<NodeArgs eType="General" icon="5" nRep="12" status="Passed" >
<Disp><![CDATA["lr_xml_get_values"]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="7/27/2017 - 11:55:06" eTime="7/27/2017 - 11:55:09" passed="3" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="8" status="Passed" >
<Disp><![CDATA[CreateOfferForCustomer Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="7" status="Passed" >
<Disp><![CDATA[CSLOfferService Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T9" iterID="2" >
<Action rID="T10">
<AName><![CDATA[CreateOfferForCustomer]]></AName>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[CreateOfferForCustomer_102]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Web service call was successful</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[7/27/2017 - 11:55:13]]></Time>
<TimeTick>1501174513</TimeTick>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[HTTP Traffic]]></Obj>
<Details plainTxt="False" ><![CDATA[HTTP Traffic]]></Details>
<Time><![CDATA[7/27/2017 - 11:55:13]]></Time>
<TimeTick>1501174513</TimeTick>
<NodeArgs eType="General" icon="4" nRep="18" >
<Disp><![CDATA[HTTP Traffic]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration2\t1_http.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="General" icon="4" nRep="17" status="Passed" >
<Disp><![CDATA[CreateOfferForCustomer_102]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration2\t1_web_service_call.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA["lr_xml_get_values"]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>"lr_xml_get_values" succeeded</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[7/27/2017 - 11:55:13]]></Time>
<TimeTick>1501174513</TimeTick>
<NodeArgs eType="General" icon="5" nRep="19" status="Passed" >
<Disp><![CDATA["lr_xml_get_values"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA["lr_xml_get_values"]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>"lr_xml_get_values" succeeded</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[7/27/2017 - 11:55:13]]></Time>
<TimeTick>1501174513</TimeTick>
<NodeArgs eType="General" icon="5" nRep="20" status="Passed" >
<Disp><![CDATA["lr_xml_get_values"]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="7/27/2017 - 11:55:12" eTime="7/27/2017 - 11:55:13" passed="3" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="16" status="Passed" >
<Disp><![CDATA[CreateOfferForCustomer Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="15" status="Passed" >
<Disp><![CDATA[CSLOfferService Iteration 2 (Row 2)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T15" iterID="3" >
<Action rID="T16">
<AName><![CDATA[CreateOfferForCustomer]]></AName>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Script Aborted!]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Pass</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[7/27/2017 - 11:55:16]]></Time>
<TimeTick>1501174516</TimeTick>
<NodeArgs eType="General" icon="1" nRep="25" >
<Disp><![CDATA[Script Aborted!]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[CreateOfferForCustomer_102]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#FF0031>Web service call failed</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[7/27/2017 - 11:55:16]]></Time>
<TimeTick>1501174516</TimeTick>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[HTTP Traffic]]></Obj>
<Details plainTxt="False" ><![CDATA[HTTP Traffic]]></Details>
<Time><![CDATA[7/27/2017 - 11:55:16]]></Time>
<TimeTick>1501174516</TimeTick>
<NodeArgs eType="General" icon="4" nRep="27" >
<Disp><![CDATA[HTTP Traffic]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="General" icon="4" nRep="26" status="Failed" >
<Disp><![CDATA[CreateOfferForCustomer_102]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="7/27/2017 - 11:55:15" eTime="7/27/2017 - 11:55:16" passed="0" failed="1" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="24" status="Failed" >
<Disp><![CDATA[CreateOfferForCustomer Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="23" status="Failed" >
<Disp><![CDATA[CSLOfferService Iteration 3 (Row 3)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T20" iterID="4" >
<Action rID="T21">
<AName><![CDATA[CreateOfferForCustomer]]></AName>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[CreateOfferForCustomer_102]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Web service call was successful</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[7/27/2017 - 11:55:17]]></Time>
<TimeTick>1501174517</TimeTick>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[HTTP Traffic]]></Obj>
<Details plainTxt="False" ><![CDATA[HTTP Traffic]]></Details>
<Time><![CDATA[7/27/2017 - 11:55:17]]></Time>
<TimeTick>1501174517</TimeTick>
<NodeArgs eType="General" icon="4" nRep="33" >
<Disp><![CDATA[HTTP Traffic]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration4\t1_http.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="General" icon="4" nRep="32" status="Passed" >
<Disp><![CDATA[CreateOfferForCustomer_102]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration4\t1_web_service_call.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA["lr_xml_get_values"]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>"lr_xml_get_values" succeeded</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[7/27/2017 - 11:55:18]]></Time>
<TimeTick>1501174518</TimeTick>
<NodeArgs eType="General" icon="5" nRep="34" status="Passed" >
<Disp><![CDATA["lr_xml_get_values"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA["lr_xml_get_values"]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>"lr_xml_get_values" succeeded</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[7/27/2017 - 11:55:18]]></Time>
<TimeTick>1501174518</TimeTick>
<NodeArgs eType="General" icon="5" nRep="35" status="Passed" >
<Disp><![CDATA["lr_xml_get_values"]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="7/27/2017 - 11:55:17" eTime="7/27/2017 - 11:55:18" passed="3" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="31" status="Passed" >
<Disp><![CDATA[CreateOfferForCustomer Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="30" status="Passed" >
<Disp><![CDATA[CSLOfferService Iteration 4 (Row 4)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T26" iterID="5" >
<Action rID="T27">
<AName><![CDATA[CreateOfferForCustomer]]></AName>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[CreateOfferForCustomer_102]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Web service call was successful</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[7/27/2017 - 11:55:22]]></Time>
<TimeTick>1501174522</TimeTick>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[HTTP Traffic]]></Obj>
<Details plainTxt="False" ><![CDATA[HTTP Traffic]]></Details>
<Time><![CDATA[7/27/2017 - 11:55:22]]></Time>
<TimeTick>1501174522</TimeTick>
<NodeArgs eType="General" icon="4" nRep="41" >
<Disp><![CDATA[HTTP Traffic]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration5\t1_http.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="General" icon="4" nRep="40" status="Passed" >
<Disp><![CDATA[CreateOfferForCustomer_102]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration5\t1_web_service_call.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA["lr_xml_get_values"]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>"lr_xml_get_values" succeeded</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[7/27/2017 - 11:55:22]]></Time>
<TimeTick>1501174522</TimeTick>
<NodeArgs eType="General" icon="5" nRep="42" status="Passed" >
<Disp><![CDATA["lr_xml_get_values"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA["lr_xml_get_values"]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>"lr_xml_get_values" succeeded</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[7/27/2017 - 11:55:22]]></Time>
<TimeTick>1501174522</TimeTick>
<NodeArgs eType="General" icon="5" nRep="43" status="Passed" >
<Disp><![CDATA["lr_xml_get_values"]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="7/27/2017 - 11:55:22" eTime="7/27/2017 - 11:55:22" passed="3" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="39" status="Passed" >
<Disp><![CDATA[CreateOfferForCustomer Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="38" status="Passed" >
<Disp><![CDATA[CSLOfferService Iteration 5 (Row 5)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T32" iterID="6" >
<Action rID="T33">
<AName><![CDATA[CreateOfferForCustomer]]></AName>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[CreateOfferForCustomer_102]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Web service call was successful</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[7/27/2017 - 11:55:26]]></Time>
<TimeTick>1501174526</TimeTick>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[HTTP Traffic]]></Obj>
<Details plainTxt="False" ><![CDATA[HTTP Traffic]]></Details>
<Time><![CDATA[7/27/2017 - 11:55:26]]></Time>
<TimeTick>1501174526</TimeTick>
<NodeArgs eType="General" icon="4" nRep="49" >
<Disp><![CDATA[HTTP Traffic]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration6\t1_http.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="General" icon="4" nRep="48" status="Passed" >
<Disp><![CDATA[CreateOfferForCustomer_102]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration6\t1_web_service_call.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA["lr_xml_get_values"]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>"lr_xml_get_values" succeeded</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[7/27/2017 - 11:55:26]]></Time>
<TimeTick>1501174526</TimeTick>
<NodeArgs eType="General" icon="5" nRep="50" status="Passed" >
<Disp><![CDATA["lr_xml_get_values"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA["lr_xml_get_values"]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>"lr_xml_get_values" succeeded</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[7/27/2017 - 11:55:26]]></Time>
<TimeTick>1501174526</TimeTick>
<NodeArgs eType="General" icon="5" nRep="51" status="Passed" >
<Disp><![CDATA["lr_xml_get_values"]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="7/27/2017 - 11:55:25" eTime="7/27/2017 - 11:55:26" passed="3" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="47" status="Passed" >
<Disp><![CDATA[CreateOfferForCustomer Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="46" status="Passed" >
<Disp><![CDATA[CSLOfferService Iteration 6 (Row 6)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T38" iterID="7" >
<Action rID="T39">
<AName><![CDATA[CreateOfferForCustomer]]></AName>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[CreateOfferForCustomer_102]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#FF0031>Web service call failed</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[7/27/2017 - 11:55:29]]></Time>
<TimeTick>1501174529</TimeTick>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[HTTP Traffic]]></Obj>
<Details plainTxt="False" ><![CDATA[HTTP Traffic]]></Details>
<Time><![CDATA[7/27/2017 - 11:55:29]]></Time>
<TimeTick>1501174529</TimeTick>
<NodeArgs eType="General" icon="4" nRep="57" >
<Disp><![CDATA[HTTP Traffic]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="General" icon="4" nRep="56" status="Failed" >
<Disp><![CDATA[CreateOfferForCustomer_102]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="7/27/2017 - 11:55:29" eTime="7/27/2017 - 11:55:29" passed="0" failed="1" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="55" status="Failed" >
<Disp><![CDATA[CreateOfferForCustomer Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="54" status="Failed" >
<Disp><![CDATA[CSLOfferService Iteration 7 (Row 7)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T42" iterID="8" >
<Action rID="T43">
<AName><![CDATA[CreateOfferForCustomer]]></AName>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[CreateOfferForCustomer_102]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Web service call was successful</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[7/27/2017 - 11:55:34]]></Time>
<TimeTick>1501174534</TimeTick>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[HTTP Traffic]]></Obj>
<Details plainTxt="False" ><![CDATA[HTTP Traffic]]></Details>
<Time><![CDATA[7/27/2017 - 11:55:34]]></Time>
<TimeTick>1501174534</TimeTick>
<NodeArgs eType="General" icon="4" nRep="63" >
<Disp><![CDATA[HTTP Traffic]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration8\t1_http.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="General" icon="4" nRep="62" status="Passed" >
<Disp><![CDATA[CreateOfferForCustomer_102]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration8\t1_web_service_call.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA["lr_xml_get_values"]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>"lr_xml_get_values" succeeded</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[7/27/2017 - 11:55:34]]></Time>
<TimeTick>1501174534</TimeTick>
<NodeArgs eType="General" icon="5" nRep="64" status="Passed" >
<Disp><![CDATA["lr_xml_get_values"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA["lr_xml_get_values"]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>"lr_xml_get_values" succeeded</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[7/27/2017 - 11:55:34]]></Time>
<TimeTick>1501174534</TimeTick>
<NodeArgs eType="General" icon="5" nRep="65" status="Passed" >
<Disp><![CDATA["lr_xml_get_values"]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="7/27/2017 - 11:55:33" eTime="7/27/2017 - 11:55:34" passed="3" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="61" status="Passed" >
<Disp><![CDATA[CreateOfferForCustomer Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="60" status="Passed" >
<Disp><![CDATA[CSLOfferService Iteration 8 (Row 8)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T48" iterID="9" >
<Action rID="T49">
<AName><![CDATA[CreateOfferForCustomer]]></AName>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[CreateOfferForCustomer_102]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Web service call was successful</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[7/27/2017 - 11:55:39]]></Time>
<TimeTick>1501174539</TimeTick>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[HTTP Traffic]]></Obj>
<Details plainTxt="False" ><![CDATA[HTTP Traffic]]></Details>
<Time><![CDATA[7/27/2017 - 11:55:39]]></Time>
<TimeTick>1501174539</TimeTick>
<NodeArgs eType="General" icon="4" nRep="71" >
<Disp><![CDATA[HTTP Traffic]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration9\t1_http.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="General" icon="4" nRep="70" status="Passed" >
<Disp><![CDATA[CreateOfferForCustomer_102]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration9\t1_web_service_call.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA["lr_xml_get_values"]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>"lr_xml_get_values" succeeded</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[7/27/2017 - 11:55:39]]></Time>
<TimeTick>1501174539</TimeTick>
<NodeArgs eType="General" icon="5" nRep="72" status="Passed" >
<Disp><![CDATA["lr_xml_get_values"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA["lr_xml_get_values"]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>"lr_xml_get_values" succeeded</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[7/27/2017 - 11:55:39]]></Time>
<TimeTick>1501174539</TimeTick>
<NodeArgs eType="General" icon="5" nRep="73" status="Passed" >
<Disp><![CDATA["lr_xml_get_values"]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="7/27/2017 - 11:55:38" eTime="7/27/2017 - 11:55:39" passed="3" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="69" status="Passed" >
<Disp><![CDATA[CreateOfferForCustomer Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="68" status="Passed" >
<Disp><![CDATA[CSLOfferService Iteration 9 (Row 9)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T54" iterID="10" >
<Action rID="T55">
<AName><![CDATA[CreateOfferForCustomer]]></AName>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[CreateOfferForCustomer_102]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Web service call was successful</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[7/27/2017 - 11:55:43]]></Time>
<TimeTick>1501174543</TimeTick>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[HTTP Traffic]]></Obj>
<Details plainTxt="False" ><![CDATA[HTTP Traffic]]></Details>
<Time><![CDATA[7/27/2017 - 11:55:43]]></Time>
<TimeTick>1501174543</TimeTick>
<NodeArgs eType="General" icon="4" nRep="79" >
<Disp><![CDATA[HTTP Traffic]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration10\t1_http.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="General" icon="4" nRep="78" status="Passed" >
<Disp><![CDATA[CreateOfferForCustomer_102]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration10\t1_web_service_call.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA["lr_xml_get_values"]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>"lr_xml_get_values" succeeded</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[7/27/2017 - 11:55:43]]></Time>
<TimeTick>1501174543</TimeTick>
<NodeArgs eType="General" icon="5" nRep="80" status="Passed" >
<Disp><![CDATA["lr_xml_get_values"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA["lr_xml_get_values"]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>"lr_xml_get_values" succeeded</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[7/27/2017 - 11:55:43]]></Time>
<TimeTick>1501174543</TimeTick>
<NodeArgs eType="General" icon="5" nRep="81" status="Passed" >
<Disp><![CDATA["lr_xml_get_values"]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="7/27/2017 - 11:55:41" eTime="7/27/2017 - 11:55:43" passed="3" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="77" status="Passed" >
<Disp><![CDATA[CreateOfferForCustomer Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="76" status="Passed" >
<Disp><![CDATA[CSLOfferService Iteration 10 (Row 10)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T60" iterID="11" >
<Action rID="T61">
<AName><![CDATA[CreateOfferForCustomer]]></AName>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[CreateOfferForCustomer_102]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Web service call was successful</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[7/27/2017 - 11:55:47]]></Time>
<TimeTick>1501174547</TimeTick>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA[HTTP Traffic]]></Obj>
<Details plainTxt="False" ><![CDATA[HTTP Traffic]]></Details>
<Time><![CDATA[7/27/2017 - 11:55:47]]></Time>
<TimeTick>1501174547</TimeTick>
<NodeArgs eType="General" icon="4" nRep="87" >
<Disp><![CDATA[HTTP Traffic]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration11\t1_http.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="General" icon="4" nRep="86" status="Passed" >
<Disp><![CDATA[CreateOfferForCustomer_102]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration11\t1_web_service_call.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA["lr_xml_get_values"]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>"lr_xml_get_values" succeeded</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[7/27/2017 - 11:55:47]]></Time>
<TimeTick>1501174547</TimeTick>
<NodeArgs eType="General" icon="5" nRep="88" status="Passed" >
<Disp><![CDATA["lr_xml_get_values"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA["lr_xml_get_values"]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>"lr_xml_get_values" succeeded</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[7/27/2017 - 11:55:47]]></Time>
<TimeTick>1501174547</TimeTick>
<NodeArgs eType="General" icon="5" nRep="89" status="Passed" >
<Disp><![CDATA["lr_xml_get_values"]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="7/27/2017 - 11:55:46" eTime="7/27/2017 - 11:55:47" passed="3" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="85" status="Passed" >
<Disp><![CDATA[CreateOfferForCustomer Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="84" status="Passed" >
<Disp><![CDATA[CSLOfferService Iteration 11 (Row 11)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T66" iterID="12" >
<Action rID="T67">
<AName><![CDATA[CreateOfferForCustomer]]></AName>
<Step rID="T68">